### ISSUE TITLE
[1.14.4] Crash whenever i tab down/minimize from the game.

### ISSUE THREAD

**Issue by Gbergz** [OreCruncher/SoundControl#4]
Title explains it really^

**Forge**: 28.1.107
**Mod Version**: 0.0.4.0
**MC Version**: 1.14.4

**Crash-Report**: https://gist.github.com/Gbergz/318e1fff7da7ff2c51056c0184c7aea9
**Logs After the Crash**: https://gist.github.com/Gbergz/8fccea741e182d58687206d9d303c774

Any ideas?

**Comment by OreCruncher** [comment]
Do you get any sounds?  Reason I ask is that the sound engine failed initialization:
```
[12:52:25] [Client thread/ERROR]: Error starting SoundSystem. Turning off sounds & music
java.lang.IllegalStateException: Failed to get OpenAL attributes
	at net.minecraft.client.audio.SoundSystem.func_216405_e(SourceFile:176) ~[?:?]
	at net.minecraft.client.audio.SoundSystem.func_216404_a(SourceFile:149) ~[?:?]
```

**Comment by OreCruncher** [comment]
I am classifying it as a bug because Sound Control should detect when Minecraft's sound engine is not initialized/loaded and not attempt a mute under those circumstances.  However, the causal issue (the crash snip above) is unknown - not sure why the sound engine is not initializing.  It's why I asked about whether sounds played at all.

**Comment by OreCruncher** [comment]
Pushed 0.0.5.0 to CurseForge.
